---RDM Manager status and report type constants.

RDM_MANAGER_WAITING = 1
RDM_MANAGER_PROGRESS = 2
RDM_MANAGER_VALID = 3
RDM_MANAGER_INVALID = 4
RDM_MANAGER_INVALID_WVW = 5
DAMAGELOG_REPORT_STANDARD = 1
DAMAGELOG_REPORT_ADMIN = 2
DAMAGELOG_REPORT_FORCE = 3
DAMAGELOG_REPORT_CHAT = 4
